#!/bin/sh

NAME='E-shop'
DJANGODIR=/saulroot/saul_3_6_4/E-shop
SOCKFILE=/saulroot/saul_3_6_4/run/gunicorn.sock
USER=sauluser
GROUP=saulgroup
NUM_WORKERS=3
DJANGO_SETTINGS_MODULE=E-shop.settingsprod
DJANGO_WSGI_MODULE=E-shop.wsgi
TIMEOUT=120

cd $DJANGODIR
source ../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --timeout $TIMEOUT \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-
