# Generated by Django 5.0.2 on 2024-02-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='used_coupon',
        ),
    ]
